version: '3'
services:
  app:
    image: shashankp28/my-project_app 
    container_name: simple-api
    command: uvicorn app.index:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      - db
  
  db:
    image: mongo:latest
    command: mongod --port 27117
    container_name: mongo
    ports:
      - 27117:27117
    volumes:
      - .data:/data/db
